<?php

/**
 * Contao Open Source CMS
 *
 * Copyright (C) 2005-2012 Leo Feyer
 *
 * @package   netzmacht-columnset
 * @author    David Molineus <http://www.netzmacht.de>
 * @license   GNU/LGPL
 * @copyright Copyright 2012 David Molineus netzmacht creative
 *
 **/

$GLOBALS['BOOTSTRAP']['form'] = array
(
	// form widgets get automatically added the form-control class. elements listed here will be skipped
	'noFormControl'     => array('button', 'submit', 'checkbox', 'radio'),

	// form widgets can be an input group
	'allowInputGroup'   => array('text', 'textarea', 'password', 'captcha'),

	// define which widgets should be generated by a template and not by the default routine
	'generateTemplates' => array
	(
		'checkbox'      => 'form_checkbox_generate',
		'radio'         => 'form_radio_generate',
	),

	// which columns shall be used for the form in table mode
	'tableFormat' => array
	(
		'label'         => 'col-lg-3',
		'control'       => 'col-lg-9',
		'offset'        => 'col-lg-offset-3',
	),

	// which controls are generated without a label. This is used to set offset in the table layout
	'noLabel'           => array('checkbox', 'radio'),

	// how to display forms like comments form by default
	'defaultTableless'  => true,

	// add style select to select list, set to false to disable
	'styleSelect' => array
	(
		'enabled'       => true,
		'class'         => 'selectpicker',
		'defaultStyle'  => 'btn-default',
		'elements'      => array('select'),
	),

	// if form is displayed in a modal these input types are displayed in the footer
	'modalFooter'       => array('button', 'submit'),

	// provides data attributes for custom select
	'dataAttributes' => array('target', 'toggle', 'dismiss', 'remote'),
);