<?php

/**
 * bootstrap configuration
 */
$GLOBALS['BOOTSTRAP'] = array
(
	'form' => array
	(
		// form widgets get automatically added the form-control class. elements listed here will be skipped
		'noFormControl'     => array('button', 'submit', 'checkbox', 'radio'),

		// form widgets can be an input group
		'allowInputGroup'   => array('text', 'textarea', 'password'),

		// define which widgets should be generated by a template and not by the default routine
		'generateTemplates' => array
		(
			'checkbox'      => 'form_checkbox_generate',
			'radio'         => 'form_radio_generate',
		),

		// which columns shall be used for the form in table mode
		'tableFormat' => array
		(
			'label'         => 'col-lg-3',
			'control'       => 'col-lg-9',
			'offset'        => 'col-lg-offset-3',
		),

		'noLabel'           => array('checkbox', 'radio'),
	),

	// The bootstrap module supports different icons sets
	'icons' => array
	(
		// Prefix for the icon class, for glyphicons the value is "glyphicons glyphicons-"
		'classPrefix'       => 'icon-',

		// the array where all icons are defined
		'set'               => include TL_ROOT . '/system/modules/bootstrap/config/icons-font-awesome.php',

		// which tag shall be used for icons
		'tag'               => 'i',
	),

	'dropdown' => array
	(
		// element which is used as download toggler
		'toggle'   => '<b class="caret"></b>',
	),


	// Define paths for autoloading templates. This is used so that only if bootstrap is activated in the layout
	// the default templates are overridden
	// You can add differnt template directories here.
	'dynamicLoadTemplates' => array
	(
		'system/modules/bootstrap/templates' => array
		(
			'form',
			'form_captcha',
			'form_checkbox',
			'form_explanation',
			'form_headline',
			'form_message',
			'form_password',
			'form_radio',
			'form_submit',
			'form_widget',
		),
	),

	'wrappers' => array
	(
		'tabs' => array
		(
			'start' => array
			(
				'name'          => 'bootstrap_tabStart',
				'triggerCreate' => true,
				'triggerDelete' => true,
			),

			'separator' => array
			(
				'name'          => 'bootstrap_tabPart',
				'autoCreate'    => true,
				'autoDelete'    => true,
				'countExisting' => array('Bootstrap\\DataContainer\\Content', 'countExistingTabSeparators'),
				'countRequired' => array('Bootstrap\\DataContainer\\Content', 'countRequiredTabSeparators'),
			),

			'stop' => array
			(
				'name'       => 'bootstrap_tabEnd',
				'autoCreate' => true,
				'autoDelete' => true,
			),
		),

		'carousel' => array
		(
			'start' => array
			(
				'name'          => 'bootstrap_carouselStart',
				'autoCreate'    => true,
				'triggerCreate' => true,
				'triggerDelete' => true,
			),

			'separator' => array
			(
				'name'          => 'bootstrap_carouselPart',
				'triggerCreate' => false,
				'autoDelete'    => true,

			),

			'stop' => array
			(
				'name'          => 'bootstrap_carouselEnd',
				'autoCreate'    => true,
				'autoDelete'    => true,
			),
		),
	),
);



/**
 * frontend modules
 */
$GLOBALS['FE_MOD']['navigationMenu']['bootstrap_navbar'] = 'Netzmacht\\Bootstrap\\ModuleNavbar';


/**
 * content elements
 */
$GLOBALS['TL_CTE']['bootstrap_carousel']['bootstrap_carouselStart'] = 'Bootstrap\\ContentCarousel';
$GLOBALS['TL_CTE']['bootstrap_carousel']['bootstrap_carouselPart']  = 'Bootstrap\\ContentCarousel';
$GLOBALS['TL_CTE']['bootstrap_carousel']['bootstrap_carouselEnd']   = 'Bootstrap\\ContentCarousel';

$GLOBALS['TL_CTE']['bootstrap_tabs']['bootstrap_tabStart']      = 'Bootstrap\\ContentTab';
$GLOBALS['TL_CTE']['bootstrap_tabs']['bootstrap_tabPart']       = 'Bootstrap\\ContentTab';
$GLOBALS['TL_CTE']['bootstrap_tabs']['bootstrap_tabEnd']        = 'Bootstrap\\ContentTab';

$GLOBALS['TL_CTE']['links']['bootstrap_button']                 = 'Bootstrap\\ContentButton';
$GLOBALS['TL_CTE']['subcolumns']['bootstrap_columnset']         = 'Bootstrap\\ContentColumnSet';


/**
 * form wigets
 */
$GLOBALS['TL_FFL']['button'] = 'Netzmacht\\Bootstrap\\FormButton';


/**
 * hooks
 */
$GLOBALS['TL_HOOKS']['parseTemplate'][] = array('Bootstrap\\DataContainer\\Bootstrap', 'initializeLayout');

$GLOBALS['TL_HOOKS']['loadFormField'][] = array('Bootstrap\\DataContainer\\Bootstrap', 'initializeFormWidget');


/**
 * wrapper
 */
$GLOBALS['TL_WRAPPERS']['start'][]      = 'bootstrap_tabStart';
$GLOBALS['TL_WRAPPERS']['stop'][]       = 'bootstrap_tabEnd';
$GLOBALS['TL_WRAPPERS']['separator'][]  = 'bootstrap_tabPart';

$GLOBALS['TL_WRAPPERS']['start'][]      = 'bootstrap_carouselStart';
$GLOBALS['TL_WRAPPERS']['stop'][]       = 'bootstrap_carouselEnd';
$GLOBALS['TL_WRAPPERS']['separator'][]  = 'bootstrap_carouselPart';


/**
 * stylesheets
 */
// add stylesheet for indented elements
if(TL_MODE == 'BE' && version_compare(VERSION, '3.1', '>=')) {
	$GLOBALS['TL_CSS'][] = 'system/modules/bootstrap/assets/css/style.css|all|static';
}