<?php

/**
 * bootstrap configuration
 */
$GLOBALS['BOOTSTRAP'] = array
(
	'form' => array
	(
		// form widgets get automatically added the form-control class. elements listed here will be skipped
		'noFormControl'     => array('button', 'submit', 'checkbox', 'radio'),

		// form widgets can be an input group
		'allowInputGroup'   => array('text', 'textarea', 'password'),

		// define which widgets should be generated by a template and not by the default routine
		'generateTemplates' => array
		(
			'checkbox'      => 'form_checkbox_generate',
			'radio'         => 'form_radio_generate',
		),

		// which columns shall be used for the form in table mode
		'tableFormat' => array
		(
			'label'         => 'col-lg-3',
			'control'       => 'col-lg-9',
			'offset'        => 'col-lg-offset-3',
		),

		'noLabel'           => array('checkbox', 'radio'),
	),

	// The bootstrap module supports different icons sets
	'icons' => array
	(
		// Prefix for the icon class, for glyphicons the value is "glyphicons glyphicons-"
		'classPrefix'       => 'icon-',

		// the array where all icons are defined
		'set'               => include TL_ROOT . '/system/modules/bootstrap/config/icons-font-awesome.php',

		// which tag shall be used for icons
		'tag'               => 'i',
	),

	'navbar' => array
	(
		// element which is used as download toggler
		'dropdownToggler'   => '<a href="#" class="button dropdown-toggle" data-toggle="dropdown"><i class="icon-caret-down"></i></a>',
	),


	// Define paths for autoloading templates. This is used so that only if bootstrap is activated in the layout
	// the default templates are overridden
	// You can add differnt template directories here.
	'dynamicLoadTemplates' => array
	(
		'system/modules/bootstrap/templates' => array
		(
			'form',
			'form_captcha',
			'form_checkbox',
			'form_explanation',
			'form_headline',
			'form_message',
			'form_password',
			'form_radio',
			'form_submit',
			'form_widget',
		),
	)
);



/**
 * frontend modules
 */
$GLOBALS['FE_MOD']['navigationMenu']['bootstrap_navbar'] = 'Netzmacht\\Bootstrap\\ModuleNavbar';


/**
 * content elements
 */
$GLOBALS['TL_CTE']['subcolumns']['bootstrap_columnset']  = 'Netzmacht\\Bootstrap\\ContentColumnSet';
$GLOBALS['TL_CTE']['links']['bootstrap_button']          = 'Netzmacht\\Bootstrap\\ContentButton';
$GLOBALS['TL_CTE']['slider']['bootstrap_slider']          = 'Netzmacht\\Bootstrap\\ContentSlider';


/**
 * form wigets
 */
$GLOBALS['TL_FFL']['button'] = 'Netzmacht\\Bootstrap\\FormButton';


/**
 * hooks
 */
$GLOBALS['TL_HOOKS']['parseTemplate'][] = array('Bootstrap\\DataContainer\\Bootstrap', 'initializeLayout');

$GLOBALS['TL_HOOKS']['loadFormField'][] = array('Bootstrap\\DataContainer\\Bootstrap', 'initializeFormWidget');