<?php

/**
 * bootstrap configuration
 */
$GLOBALS['BOOTSTRAP'] = array
(
	'form' => array
	(
		// form widgets get automatically added the form-control class. elements listed here will be skipped
		'noFormControl'     => array('button', 'submit', 'checkbox', 'radio'),

		// form widgets can be an input group
		'allowInputGroup'   => array('text', 'textarea', 'password'),

		// define which widgets should be generated by a template and not by the default routine
		'generateTemplates' => array
		(
			'checkbox'      => 'form_checkbox_generate',
			'radio'         => 'form_radio_generate',
		),

		// which columns shall be used for the form in table mode
		'tableFormat' => array
		(
			'label'         => 'col-lg-3',
			'control'       => 'col-lg-9',
			'offset'        => 'col-lg-offset-3',
		),

		// which controls are generated without a label. This is used to set offset in the table layout
		'noLabel'           => array('checkbox', 'radio'),

		// how to display forms like comments form by default
		'defaultTableless'  => true,
	),

	// The bootstrap module supports different icons sets
	'icons' => array
	(
		// registered icons sets
		'sets' => array
		(
			'font-awesome'  => array
			(
				'path'      => 'system/modules/bootstrap/config/icons-font-awesome.php',
				'template'  => '<i class="icon-%s"></i>',
			),
			'glyphicons'    => array
			(
				'path'      => 'system/modules/bootstrap/config/icons-glyphicons.php',
				'template'  => '<span class="glyphicon glyphicon-%s"></span>',
			),
		),

		// the array where all icons are defined
		''                  => array(),

		// which tag shall be used for icons
		'template'          => array(),
	),

	'dropdown' => array
	(
		// element which is used as download toggler
		'toggle'   => '<b class="caret"></b>',
	),


	// Define paths for autoloading templates. This is used so that only if bootstrap is activated in the layout
	// the default templates are overridden
	// You can add differnt template directories here.
	'dynamicLoadTemplates' => array
	(
		'system/modules/bootstrap/templates/theme' => array
		(
			'ce_accordion',
			'ce_accordion_start',
			'form',
			'form_captcha',
			'form_checkbox',
			'form_explanation',
			'form_headline',
			'form_message',
			'form_password',
			'form_radio',
			'form_submit',
			'form_widget',
			'mod_comment_form',
			'mod_search_advanced',
		),
	),

	// Wrappers are content elements containing a start, separators and stop elements
	// If they are created a generic callback checks how to create or delete the containing elements
	// Only change this config if you know what you are doing!
	'wrappers' => array
	(
		// Bootstrap tab component
		'tabs' => array
		(
			'start' => array
			(
				'name'          => 'bootstrap_tabStart',
				'triggerCreate' => true, // auto create separators and stop element
				'triggerDelete' => true, // auto deleete separators and stop element
			),

			'separator' => array
			(
				'name'          => 'bootstrap_tabPart',
				'autoCreate'    => true, // can be auto created
				'autoDelete'    => true, // can be auto deleted

				// callback to detect how many separators exists
				'countExisting' => array('Bootstrap\\DataContainer\\Content', 'countExistingTabSeparators'),

				// callback to detect how many separators are required
				'countRequired' => array('Bootstrap\\DataContainer\\Content', 'countRequiredTabSeparators'),
			),

			'stop' => array
			(
				'name'       => 'bootstrap_tabEnd',
				'autoCreate' => true,
				'autoDelete' => true,
			),
		),

		// Bootstrap carousel component
		'carousel' => array
		(
			'start' => array
			(
				'name'          => 'bootstrap_carouselStart',
				'autoCreate'    => true,
				'triggerCreate' => true,
				'triggerDelete' => true,
			),

			'separator' => array
			(
				'name'          => 'bootstrap_carouselPart',
				'triggerCreate' => false,
				'autoDelete'    => true,

			),

			'stop' => array
			(
				'name'          => 'bootstrap_carouselEnd',
				'autoCreate'    => true,
				'autoDelete'    => true,
			),
		),

		'accordion' => array
		(
			'start' => array
			(
				'name'          => 'bootstrap_accordionGroupStart',
				'autoCreate'    => true,
				'autoDelete'    => true,
				'triggerCreate' => true,
				'triggerDelete' => true,
			),

			'stop' => array
			(
				'name'          => 'bootstrap_accordionGroupEnd',
				'autoCreate'    => true,
				'autoDelete'    => true,
				'triggerCreate' => true,
				'triggerDelete' => true,
			),
		),
	),
);

/**
 * backend modules
 */


/**
 * frontend modules
 */
$GLOBALS['FE_MOD']['navigationMenu']['bootstrap_navbar'] = 'Netzmacht\\Bootstrap\\ModuleNavbar';


/**
 * content elements
 */
$GLOBALS['TL_CTE']['bootstrap_carousel']['bootstrap_carouselStart'] = 'Bootstrap\\ContentCarousel';
$GLOBALS['TL_CTE']['bootstrap_carousel']['bootstrap_carouselPart']  = 'Bootstrap\\ContentCarousel';
$GLOBALS['TL_CTE']['bootstrap_carousel']['bootstrap_carouselEnd']   = 'Bootstrap\\ContentCarousel';

$GLOBALS['TL_CTE']['bootstrap_tabs']['bootstrap_tabStart']      = 'Bootstrap\\ContentTab';
$GLOBALS['TL_CTE']['bootstrap_tabs']['bootstrap_tabPart']       = 'Bootstrap\\ContentTab';
$GLOBALS['TL_CTE']['bootstrap_tabs']['bootstrap_tabEnd']        = 'Bootstrap\\ContentTab';

$GLOBALS['TL_CTE']['accordion']['bootstrap_accordionGroupStart']      = 'Bootstrap\\ContentAccordionGroup';
$GLOBALS['TL_CTE']['accordion']['bootstrap_accordionGroupEnd']        = 'Bootstrap\\ContentAccordionGroup';


$GLOBALS['TL_CTE']['links']['bootstrap_button']                 = 'Bootstrap\\ContentButton';
$GLOBALS['TL_CTE']['subcolumns']['bootstrap_columnset']         = 'Bootstrap\\ContentColumnSet';


/**
 * form wigets
 */
$GLOBALS['TL_FFL']['button'] = 'Netzmacht\\Bootstrap\\FormButton';


/**
 * hooks
 */
if(version_compare(VERSION, '3.1', '>0'))
{
	$GLOBALS['TL_HOOKS']['getPageLayout'][] = array('Bootstrap\\DataContainer\\Bootstrap', 'initializeLayout');
}
else
{
	$GLOBALS['TL_HOOKS']['parseTemplate'][] = array('Bootstrap\\DataContainer\\Bootstrap', 'initializeLayoutByParseTemplateHook');
}

$GLOBALS['TL_HOOKS']['loadFormField'][] = array('Bootstrap\\DataContainer\\Bootstrap', 'initializeFormWidget');

/**
 * config values
 */
$GLOBALS['TL_CONFIG']['bootstrapIconSet'] = 'font-awesome';

/**
 * wrapper
 */
$GLOBALS['TL_WRAPPERS']['start'][]      = 'bootstrap_accordionGroupStart';
$GLOBALS['TL_WRAPPERS']['stop'][]       = 'bootstrap_accordionGroupEnd';

$GLOBALS['TL_WRAPPERS']['start'][]      = 'bootstrap_tabStart';
$GLOBALS['TL_WRAPPERS']['stop'][]       = 'bootstrap_tabEnd';
$GLOBALS['TL_WRAPPERS']['separator'][]  = 'bootstrap_tabPart';

$GLOBALS['TL_WRAPPERS']['start'][]      = 'bootstrap_carouselStart';
$GLOBALS['TL_WRAPPERS']['stop'][]       = 'bootstrap_carouselEnd';
$GLOBALS['TL_WRAPPERS']['separator'][]  = 'bootstrap_carouselPart';


/**
 * stylesheets
 */
// add stylesheet for indented elements
if(TL_MODE == 'BE' && version_compare(VERSION, '3.1', '>=')) {
	$GLOBALS['TL_CSS'][] = 'system/modules/bootstrap/assets/css/style.css|all|static';
}